export const DELETE_CONFIRMATION_MODAL = 'DELETE_CONFIRMATION_MODAL';

export const CREATE_ADMIN_SPONSORS_MODAL = 'CREATE_ADMIN_SPONSORS_MODAL';
export const UPDATE_ADMIN_SPONSORS_MODAL = 'UPDATE_ADMIN_SPONSORS_MODAL';
export const UPDATE_ADMIN_SPONSORS_IMAGE_MODAL =
  'UPDATE_ADMIN_SPONSORS_IMAGE_MODAL';
